### PR TITLE
Support downloading into a folder with a space

### PR DESCRIPTION
**Pull request by amalkh5**
## Description

This commit will add support for downloading Faas-cli into a folder with space.

Signed-off-by: Amal Alkhamees <amalkms5@gmail.com>

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
Before adding the commit, if you install Faas-cli into a folder with spaces in the name you will get

```
$  pwd
/Users/amal/go/src/github.com/openfaas/faas-cli/t est

$ curl -sSL https://cli.openfaas.com | sh
Finding latest version from GitHub
0.12.2
sh: line 105: [: /Users/amal/go/src/github.com/openfaas/faas-cli/t: binary operator expected
Downloading package https://github.com/openfaas/faas-cli/releases/download/0.12.2/faas-cli-darwin as /Users/amal/go/src/github.com/open
faas/faas-cli/t est/faas-cli-darwin
curl: (6) Could not resolve host: est

```
After adding the commit 
```
$  pwd
/Users/amal/go/src/github.com/openfaas/cli.openfaas.com/t est

$ sudo sh ../get.sh   
Password:
Finding latest version from GitHub
0.12.2
Downloading package https://github.com/openfaas/faas-cli/releases/download/0.12.2/faas-cli-darwin as /tmp/faas-cli-darwin
Download complete.

Running with sufficient permissions to attempt to move faas-cli to /usr/local/bin
New version of faas-cli installed to /usr/local/bin
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  2d183c713b32385831dc7f69c073e57c06e3b76c
 version: 0.12.2

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.18.11
 sha:     326cc7a9b9235276ecf38430c49a5707a429c6c8
 commit:  Add featured videos section to community file


Provider
 name:          faas-swarm
 orchestration: swarm
 version:       0.8.2 
 sha:           47988f8ba284678f3eb86eb62f75f72bafeec4d9
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Review by LucasRoesler — CHANGES_REQUESTED** [review]
I think there some quotes are missing on line 59 too

```sh
Finding latest version from GitHub
0.12.2
Downloading package https://github.com/openfaas/faas-cli/releases/download/0.12.2/faas-cli-darwin as /Users/lucasroesler/Code/openfaas/cli.openfaas.com/test here/faas-cli-darwin
../get.sh: line 59: cd: /Users/lucasroesler/Code/openfaas/cli.openfaas.com/test: No such file or directory
rm: /Users/lucasroesler/Code/openfaas/cli.openfaas.com/test: No such file or directory
rm: here/faas-cli-darwin: No such file or directory
Binary checksum didn't match. Exiting
```

**Comment by amalkh5** [comment]
@LucasRoesler fixed
```
$ sh ../get.sh
Finding latest version from GitHub
0.12.2
Downloading package https://github.com/openfaas/faas-cli/releases/download/0.12.2/faas-cli-darwin as /Users/amal/go/src/github.com/openfaas/cli.openfaas.com/t set/faas-cli-darwin
Download complete.

Running with sufficient permissions to attempt to move faas-cli to /usr/local/bin
New version of faas-cli installed to /usr/local/bin
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  2d183c713b32385831dc7f69c073e57c06e3b76c
 version: 0.12.2

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.18.11
 sha:     326cc7a9b9235276ecf38430c49a5707a429c6c8
 commit:  Add featured videos section to community file


Provider
 name:          faas-swarm
 orchestration: swarm
 version:       0.8.2 
 sha:           47988f8ba284678f3eb86eb62f75f72bafeec4d9

```

**Comment by LucasRoesler** [comment]
👍 worked for me

```sh
➜  test here git:(fix-space-issue) bash ../get.sh $(pwd)
Finding latest version from GitHub
0.12.2
Downloading package https://github.com/openfaas/faas-cli/releases/download/0.12.2/faas-cli-darwin as /Users/lucasroesler/Code/openfaas/cli.openfaas.com/test here/faas-cli-darwin
Download complete.

Running with sufficient permissions to attempt to move faas-cli to /usr/local/bin
New version of faas-cli installed to /usr/local/bin
Creating alias 'faas' for 'faas-cli'.
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  2d183c713b32385831dc7f69c073e57c06e3b76c
 version: 0.12.2
```

**Review by LucasRoesler — APPROVED** [review]
@alexellis this is read to merge

**Comment by LucasRoesler** [comment]
bump @alexellis

**Comment by alexellis** [comment]
Thanks for the ping. Let me do that now

**Pull request merged**
